### ISSUE TITLE
Support windows

### ISSUE THREAD

**Issue by sinchb** [quatanium/python-onvif#1]

**Comment by rgreimel** [comment]
pip.exe install onvif
gives the following error:
running install_data
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "d:\users\olg\appdata\local\temp\pip_build_olg\onvif\setup.py", line 49, in <module>
    'console_scripts': ['onvif-cli = onvif.cli:main']
  File "C:\Python27\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python27\lib\site-packages\setuptools\command\install.py", line 61, i n run
    return orig.install.run(self)
  File "C:\Python27\lib\distutils\command\install.py", line 575, in run
    self.run_command(cmd_name)
  File "C:\Python27\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python27\lib\distutils\command\install_data.py", line 58, in run
    dir = convert_path(f[0])
  File "C:\Python27\lib\distutils\util.py", line 124, in convert_path
    raise ValueError, "path '%s' cannot be absolute" % pathname
ValueError: path '/etc/onvif/wsdl' cannot be absolute

**Comment by sinchb** [comment]
sorry for this. onvif for windows is not supported now.

**Comment by pdhammond** [comment]
Fix for this appears to be simple, just replace "/etc" with "c:/ProgramData" in the data_files parameter if the latter exists and the former doesn't. Then set the wsdl parameter in ONVIFCamera().

**Comment by mpromonet** [comment]
Since this commit ebc1344b22ec66187c5cee3db97777db35137720 the wsdl are installed inside the package. Then it should work with windows when pip repository will point to a new release.

**Comment by sinchb** [comment]
@mpromonet I will test this feature this weekend. Thand you.

**Comment by dashesy** [comment]
I get this error:
    
    ImportError: No module named 'client'

And installing suds-jurko did not fix it

**Comment by Efreeto** [comment]
Onvif was able to run on Windows successfully with these changes:
1) Using Python 2 (not 3)
2) Replacing ONVIFCamera(,,,,**'/etc/onvif/wsdl/'**) with ONVIFCamera(,,,,**'C:\\Python27\\wsdl\\'**)
