### ISSUE TITLE
Example how to set IPv4Configuration?

### ISSUE THREAD

**Issue by hackeron** [quatanium/python-onvif#10]
Specifically it would be great to have an example for how to enable DHCP. I am trying to do mycam.devicemgmt.IPv4Configuration but it says Method not found. Not quite sure which method to use.

**Comment by sinchb** [comment]
IPv4Configuration isn't a method defined by onvif. I think [this](http://www.onvif.org/onvif/ver10/device/wsdl/devicemgmt.wsdl#op.SetNetworkInterfaces) is what you want. all the operations can find [here](http://www.onvif.org/onvif/ver20/util/operationIndex.html)

**Comment by hackeron** [comment]
Ah, thank you, I am still struggling though, I tried to do this:

```python
>>> from onvif import ONVIFCamera
>>> mycam = ONVIFCamera('192.168.88.11', 80, 'admin', '', '/usr/local/lib/python2.7/site-packages/etc/onvif/wsdl/')
>>> network_interfaces = mycam.devicemgmt.create_type('SetNetworkInterfaces')
>>> network_interfaces.NetworkInterface.IPv4.DHCP = True
>>> network_interfaces.NetworkInterface.IPv4.DHCP
True
>>> mycam.devicemgmt.SetNetworkInterfaces(network_interfaces)
False
>>> # Hmmm, another try...
>>> network_interfaces = mycam.devicemgmt.GetNetworkInterfaces()
>>> network_interfaces[0].IPv4.Config.DHCP = True
>>> network_interfaces[0].IPv4.Config.DHCP
True
>>> mycam.devicemgmt.SetNetworkInterfaces(network_interfaces[0])
False
```

Any ideas?

**Comment by sinchb** [comment]
well,  [here](http://www.onvif.org/Portals/0/documents/WhitePapers/ONVIF_WG-APG-Application_Programmer's_Guide.pdf) is an example to set the network interface(page 22). 

I think your passed wrong parameter to ``SetNetworkInterfaces``.
 this will work?

```python
mycam.devicemgmt.SetNetworkInterfaces(network_interfaces)
```

**Comment by hackeron** [comment]
That's the first thing I tried, if I do that I get this output:

```python
>>> from onvif import ONVIFCamera
>>> mycam = ONVIFCamera('192.168.88.11', 80, 'admin', '', '/usr/local/lib/python2.7/site-packages/etc/onvif/wsdl/')
>>> network_interfaces = mycam.devicemgmt.GetNetworkInterfaces()
>>> network_interfaces[0].IPv4.Config.DHCP = True
>>> network_interfaces[0].IPv4.Config.DHCP
True
>>> mycam.devicemgmt.SetNetworkInterfaces(network_interfaces)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/onvif/client.py", line 28, in wrapped
    raise ONVIFError(err)
onvif.exceptions.ONVIFError: Unknown error: Method instance argument after ** must be a mapping, not list```

**Comment by sinchb** [comment]
I think you missed one parameter: InterfaceToken,  look at [this](http://www.onvif.org/onvif/ver10/device/wsdl/devicemgmt.wsdl#op.SetNetworkInterfaces)

**Comment by hackeron** [comment]
Doesn't seem to help:

```python
>>> from onvif import ONVIFCamera
>>> mycam = ONVIFCamera('192.168.88.11', 80, 'admin', '', '/usr/local/lib/python2.7/site-packages/etc/onvif/wsdl/')
>>> network_interfaces = mycam.devicemgmt.GetNetworkInterfaces()
>>> network_interfaces[0]['Info']['Name']
Test
>>> network_interfaces[0].IPv4.Config.DHCP = True
>>> mycam.devicemgmt.SetNetworkInterface('Test',  network_interfaces[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/onvif/client.py", line 177, in __getattr__
    return self.service_wrapper(getattr(self.ws_client.service, name))
  File "/usr/local/lib/python2.7/site-packages/suds/client.py", line 299, in __getattr__
    return getattr(port, name)
  File "/usr/local/lib/python2.7/site-packages/suds/client.py", line 403, in __getattr__
    return getattr(m, name)
  File "/usr/local/lib/python2.7/site-packages/suds/client.py", line 494, in __getattr__
    return self[name]
  File "/usr/local/lib/python2.7/site-packages/suds/client.py", line 507, in __getitem__
    raise MethodNotFound, qn
suds.MethodNotFound: Method not found: 'DeviceService.DevicePort.SetNetworkInterface'
>>> mycam.devicemgmt.SetNetworkInterface('Test',  network_interfaces)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/onvif/client.py", line 177, in __getattr__
    return self.service_wrapper(getattr(self.ws_client.service, name))
  File "/usr/local/lib/python2.7/site-packages/suds/client.py", line 299, in __getattr__
    return getattr(port, name)
  File "/usr/local/lib/python2.7/site-packages/suds/client.py", line 403, in __getattr__
    return getattr(m, name)
  File "/usr/local/lib/python2.7/site-packages/suds/client.py", line 494, in __getattr__
    return self[name]
  File "/usr/local/lib/python2.7/site-packages/suds/client.py", line 507, in __getitem__
    raise MethodNotFound, qn
suds.MethodNotFound: Method not found: 'DeviceService.DevicePort.SetNetworkInterface'
```

Can you provide an example of something that works for you with one of your cameras?

**Comment by sinchb** [comment]
There is no method named "SetNetworkInterface",  It is ** SetNetworkInterfaces**

**Comment by hackeron** [comment]
Alright, here's what I see then:

```python
>>> from onvif import ONVIFCamera
>>> mycam = ONVIFCamera('192.168.88.11', 80, 'admin', '', '/usr/local/lib/python2.7/site-packages/etc/onvif/wsdl/')
>>> network_interfaces = mycam.devicemgmt.GetNetworkInterfaces()
>>> network_interfaces[0]['Info']['Name']
Test
>>> network_interfaces[0].IPv4.Config.DHCP = True
>>> mycam.devicemgmt.SetNetworkInterfaces('Test',  network_interfaces[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/onvif/client.py", line 28, in wrapped
    raise ONVIFError(err)
onvif.exceptions.ONVIFError: Unknown error: Method instance argument after ** must be a mapping, not str
>>>
>>>
>>> mycam.devicemgmt.SetNetworkInterfaces('Test',  network_interfaces)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/onvif/client.py", line 28, in wrapped
    raise ONVIFError(err)
onvif.exceptions.ONVIFError: Unknown error: Method instance argument after ** must be a mapping, not str
```

**Comment by sinchb** [comment]
well, the way you passed the parameters isn't correct... Please read the onvif [doc](https://github.com/quatanium/python-onvif#configure-control-your-camera), and ``type instance`` is the recommended.

BTW, I think the value of ``Token`` in you configuration is "Token", while "Test" is the value of "info.Name"

**Comment by hackeron** [comment]
I can't pass params I got from GetNetworkInterfaces?

Also, "Token" doesn't seem to work either.

```python
>>>  network_interfaces = mycam.devicemgmt.GetNetworkInterfaces()
>>> mycam.devicemgmt.SetNetworkInterfaces('Token',  network_interfaces)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/onvif/client.py", line 28, in wrapped
    raise ONVIFError(err)
onvif.exceptions.ONVIFError: Unknown error: Method instance argument after ** must be a mapping, not str
>>> mycam.devicemgmt.SetNetworkInterfaces('Token',  network_interfaces[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/onvif/client.py", line 28, in wrapped
    raise ONVIFError(err)
onvif.exceptions.ONVIFError: Unknown error: Method instance argument after ** must be a mapping, not str
```

Do you have a working example of setting networking?

**Comment by hackeron** [comment]
OK, I tried to use a type instance, also a no go :(

```python
>>> from onvif import ONVIFCamera
>>> mycam = ONVIFCamera('192.168.88.11', 80, 'admin', '', '/usr/local/lib/python2.7/site-packages/etc/onvif/wsdl/')
>>> params = mycam.devicemgmt.create_type('SetNetworkInterfaces')
>>> params.InterfaceToken = "Token"
>>> params.NetworkInterface.IPv4.DHCP = True
>>> mycam.devicemgmt.SetNetworkInterfaces(params)
False
>>> params.InterfaceToken = "Test"
>>> mycam.devicemgmt.SetNetworkInterfaces(params)
False
```

Any ideas?

**Comment by sinchb** [comment]
ehhh... I think your code worked. ``False`` is the response of ``SetNetworkInterfaes`` from camrea. It indicates whether or not a reboot is required after configuration updates.  see the response [definition](http://www.onvif.org/onvif/ver10/device/wsdl/devicemgmt.wsdl#op.SetNetworkInterfaces) of ``SetNetworkInterfaces``

**Comment by hackeron** [comment]
Unfortunately not :( 

<img width="1240" alt="screen shot 2015-07-28 at 11 08 35" src="https://cloud.githubusercontent.com/assets/578881/8928843/05d784dc-3519-11e5-9a22-27765120d25e.png">

**Comment by sinchb** [comment]
really strange... well, sorry for that. I will test on my camera tomorrow, and then i'll tell you the result.

**Comment by hackeron** [comment]
Thank you :)

**Comment by sinchb** [comment]
Here is my result, everything is OK....

```python
In [14]: mycam.devicemgmt.GetNetworkInterfaces()
Out[14]:
[(NetworkInterface){
    _token = "eth0"
    Enabled = True
    Info =
       (NetworkInterfaceInfo){
          Name = "eth0"
          HwAddress = "c4:2f:90:13:11:15"
          MTU = 1500
       }
    Link =
       (NetworkInterfaceLink){
          AdminSettings =
             (NetworkInterfaceConnectionSetting){
                AutoNegotiation = True
                Speed = 100
                Duplex = "Full"
             }
          OperSettings =
             (NetworkInterfaceConnectionSetting){
                AutoNegotiation = True
                Speed = 100
                Duplex = "Full"
             }
          InterfaceType = "0"
       }
    IPv4 =
       (IPv4NetworkInterface){
          Enabled = True
          Config =
             (IPv4Configuration){
                Manual[] =
                   (PrefixedIPv4Address){
                      Address = "192.168.100.173"
                      PrefixLength = 24
                   },
                DHCP = False
             }
       }
    IPv6 =
       (IPv6NetworkInterface){
          Enabled = True
          Config =
             (IPv6Configuration){
                AcceptRouterAdvert = False
                DHCP = "Off"
                LinkLocal[] =
                   (PrefixedIPv6Address){
                      Address = "fe80::c62f:90ff:fe13:1115"
                      PrefixLength = 64
                   },
                FromDHCP[] =
                   (PrefixedIPv6Address){
                      Address = "fe80::c62f:90ff:fe13:1115"
                      PrefixLength = 64
                   },
             }
       }
  }, (NetworkInterface){
    _token = "wlan0"
    Enabled = False
    Info =
       (NetworkInterfaceInfo){
          Name = "wlan0"
          HwAddress = "8c:18:d9:62:ad:4c"
          MTU = 1500
       }
    IPv4 =
       (IPv4NetworkInterface){
          Enabled = True
          Config =
             (IPv4Configuration){
                FromDHCP =
                   (PrefixedIPv4Address){
                      Address = "169.254.38.101"
                      PrefixLength = 16
                   }
                DHCP = True
             }
       }
  }]

In [15]: params = mycam.devicemgmt.create_type('SetNetworkInterfaces')

In [16]: params.InterfaceToken='eth0'

In [17]: params.NetworkInterface.Enabled=True

In [18]: params.NetworkInterface.IPv4.Enabled = True

In [19]: params.NetworkInterface.IPv4.DHCP = True

In [20]: print mycam.devicemgmt.SetNetworkInterfaces(params)
True

In [21]: mycam.devicemgmt.GetNetworkInterfaces()
Out[21]:
[(NetworkInterface){
    _token = "eth0"
    Enabled = True
    Info =
       (NetworkInterfaceInfo){
          Name = "eth0"
          HwAddress = "c4:2f:90:13:11:15"
          MTU = 1500
       }
    Link =
       (NetworkInterfaceLink){
          AdminSettings =
             (NetworkInterfaceConnectionSetting){
                AutoNegotiation = True
                Speed = 100
                Duplex = "Full"
             }
          OperSettings =
             (NetworkInterfaceConnectionSetting){
                AutoNegotiation = True
                Speed = 100
                Duplex = "Full"
             }
          InterfaceType = "0"
       }
    IPv4 =
       (IPv4NetworkInterface){
          Enabled = True
          Config =
             (IPv4Configuration){
                FromDHCP =
                   (PrefixedIPv4Address){
                      Address = "192.168.100.173"
                      PrefixLength = 24
                   }
                DHCP = True
             }
       }
    IPv6 =
       (IPv6NetworkInterface){
          Enabled = True
          Config =
             (IPv6Configuration){
                AcceptRouterAdvert = False
                DHCP = "Off"
                LinkLocal[] =
                   (PrefixedIPv6Address){
                      Address = "fe80::c62f:90ff:fe13:1115"
                      PrefixLength = 64
                   },
                FromDHCP[] =
                   (PrefixedIPv6Address){
                      Address = "fe80::c62f:90ff:fe13:1115"
                      PrefixLength = 64
                   },
             }
       }
  }, (NetworkInterface){
    _token = "wlan0"
    Enabled = False
    Info =
       (NetworkInterfaceInfo){
          Name = "wlan0"
          HwAddress = "8c:18:d9:62:ad:4c"
          MTU = 1500
       }
    IPv4 =
       (IPv4NetworkInterface){
          Enabled = True
          Config =
             (IPv4Configuration){
                FromDHCP =
                   (PrefixedIPv4Address){
                      Address = "169.254.38.101"
                      PrefixLength = 16
                   }
                DHCP = True
             }
       }
  }]

```

what is the camera brand? Maybe you can reset your camera and try again.

**Comment by xanview** [comment]
This is a Chinese no brand camera, so it is possibly faulty, but the ruby library works, so not sure what it is doing that is different. I tried the above basing it on your example and I get this:

```
>>> mycam.devicemgmt.GetNetworkInterfaces()
WARNING:suds.umx.typed:attribute (DeviceEntity) type, not-found
[(NetworkInterface){
   _DeviceEntity = "Token"
   Enabled = True
   Info = 
      (NetworkInterfaceInfo){
         Name = "Test"
         HwAddress = "00:fc:14:0e:00:05"
         MTU = 1500
      }
   Link = 
      (NetworkInterfaceLink){
         AdminSettings = 
            (NetworkInterfaceConnectionSetting){
               AutoNegotiation = True
               Speed = 100
               Duplex = "Full"
            }
         OperSettings = 
            (NetworkInterfaceConnectionSetting){
               AutoNegotiation = True
               Speed = 100
               Duplex = "Full"
            }
         InterfaceType = "0"
      }
   IPv4 = 
      (IPv4NetworkInterface){
         Enabled = True
         Config = 
            (IPv4Configuration){
               DHCP = False
               Manual[] = 
                  (PrefixedIPv4Address){
                     Address = "192.168.88.11"
                     PrefixLength = 23
                  },
               LinkLocal = 
                  (PrefixedIPv4Address){
                     Address = "192.168.88.11"
                     PrefixLength = 23
                  }
               FromDHCP = 
                  (PrefixedIPv4Address){
                     Address = "192.168.88.11"
                     PrefixLength = 23
                  }
            }
      }
 }]
>>> interfaces = mycam.devicemgmt.GetNetworkInterfaces()
WARNING:suds.umx.typed:attribute (DeviceEntity) type, not-found
>>> params = mycam.devicemgmt.create_type('SetNetworkInterfaces')
>>> params.InterfaceToken='Test'
>>> params.NetworkInterface.Enabled=True
>>> params.NetworkInterface.IPv4.Enabled = True
>>> params.NetworkInterface.IPv4.DHCP = True
>>> print mycam.devicemgmt.SetNetworkInterfaces(params)
False
>>> mycam.devicemgmt.GetNetworkInterfaces()
WARNING:suds.umx.typed:attribute (DeviceEntity) type, not-found
[(NetworkInterface){
   _DeviceEntity = "Token"
   Enabled = True
   Info = 
      (NetworkInterfaceInfo){
         Name = "Test"
         HwAddress = "00:fc:14:0e:00:05"
         MTU = 1500
      }
   Link = 
      (NetworkInterfaceLink){
         AdminSettings = 
            (NetworkInterfaceConnectionSetting){
               AutoNegotiation = True
               Speed = 100
               Duplex = "Full"
            }
         OperSettings = 
            (NetworkInterfaceConnectionSetting){
               AutoNegotiation = True
               Speed = 100
               Duplex = "Full"
            }
         InterfaceType = "0"
      }
   IPv4 = 
      (IPv4NetworkInterface){
         Enabled = True
         Config = 
            (IPv4Configuration){
               DHCP = False
               Manual[] = 
                  (PrefixedIPv4Address){
                     Address = "192.168.88.11"
                     PrefixLength = 23
                  },
               LinkLocal = 
                  (PrefixedIPv4Address){
                     Address = "192.168.88.11"
                     PrefixLength = 23
                  }
               FromDHCP = 
                  (PrefixedIPv4Address){
                     Address = "192.168.88.11"
                     PrefixLength = 23
                  }
            }
      }
 }]
```

**Comment by molobrakos** [comment]
This works for me to change the default IP from `192.168.1.10` to `192.168.1.20` ("chinese camera" from AliExpress):
```python
mgmt.SetNetworkInterfaces(dict(
    InterfaceToken='eth0',     
    NetworkInterface=dict(     
        IPv4=dict(
            Enabled=True,
            Manual=[dict(
                Address='192.168.1.20',
                PrefixLength=24)],
            DHCP=False)))))
```

`mgmt.GetDeviceInformation()` returns
```
(reply){
   Manufacturer = "H264"
   Model = "50H20L_S39"
   FirmwareVersion = "V4.02.R11.00002520.10010.244000..ONVIF 2.4"
   SerialNumber = "2b874578dfb749b9"
   HardwareId = "00001"
 }

```
