### ISSUE TITLE
Connection aborted. RemoteDisconnected('Remote end closed connection without response',)

### ISSUE THREAD

**Issue by hgebrema** [quatanium/python-onvif#102]
Hi,
I'm having issues with the SendReceiveSerialCommand() function of the deviceIO service. I can succesfully get the serial port token using GetSerialPorts() and the port configurations using SetSerialPortConfiguration(), however when I try to send data like this
```
ports = self.deviceio_service.GetSerialPorts()
self.token_serial = ports[0].token

serial_data = {
    'Token': self.token_serial,
    'SerialData': b"\x01\x02\x04\x07\x02\x0f",
    'TimeOut': "PT0M0.1S",
    'DataLength': "100",
    'Delimiter': "",
}

self.deviceio_service.SendReceiveSerialCommand(serial_data)
```

I get the error
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.5/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/lib/python3.5/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/usr/lib/python3.5/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.5/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.5/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.5/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/lib/python3.5/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/onvif/client.py", line 23, in wrapped
    return func(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/onvif/client.py", line 153, in wrapped
    return call(params, callback)
  File "/usr/lib/python3.5/site-packages/onvif/client.py", line 143, in call
    ret = func(params)
  File "/usr/lib/python3.5/site-packages/zeep/proxy.py", line 45, in __call__
    kwargs,
  File "/usr/lib/python3.5/site-packages/zeep/wsdl/bindings/soap.py", line 122, in send
    response = client.transport.post_xml(options["address"], envelope, http_headers)
  File "/usr/lib/python3.5/site-packages/zeep/transports.py", line 95, in post_xml
    return self.post(address, message, headers)
  File "/usr/lib/python3.5/site-packages/zeep/transports.py", line 62, in post
    address, data=message, headers=headers, timeout=self.operation_timeout
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 571, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 634, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.5/site-packages/requests/adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "controller_onvif.py", line 147, in <module>
    main()
  File "controller_onvif.py", line 88, in main
    new_brightness = current_cam.set_brightness(brightness)
  File "/home/root/controller_onvif/custom_onvif_camera.py", line 354, in set_brightness
    send_receive = self.deviceio_service.SendReceiveSerialCommand(serial_data)
  File "/usr/lib/python3.5/site-packages/onvif/client.py", line 26, in wrapped
    raise ONVIFError(err)
onvif.exceptions.ONVIFError: Unknown error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

```

I can use the media and imaging services without issues. I can send commands to the port using a web page so I know the connection should be open. Any ideas?

**Comment by karryor** [comment]
Hello, I reported the same error when using ONVIFCamera() to access the camera. Do you know the solution?

**Comment by hgebrema** [comment]
For me it turns out that my deviceIO wsdl file was missing the token parameter in the SendReceiveSerialCommand

**Comment by matheusvellone** [comment]
@hgebrema do you mind sharing exactly you did to fix it? I'm having a similiar problem reported on https://github.com/FalkTannhaeuser/python-onvif-zeep/issues/122
