### ISSUE TITLE
onvif not installing using pip

### ISSUE THREAD

**Issue by dipcb05** [quatanium/python-onvif#103]
i also try to install onvif 0.4 using pip.

error:

pip install suds==0.4
Collecting suds==0.4
Using cached suds-0.4.tar.gz (104 kB)
ERROR: Command errored out with exit status 1:
command: /home/dip05/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lsy9asid/suds_55a5bbb1e4954c50bf56df351e6e7092/setup.py'"'"'; file='"'"'/tmp/pip-install-lsy9asid/suds_55a5bbb1e4954c50bf56df351e6e7092/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(file) if os.path.exists(file) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-1gjn0vm8
cwd: /tmp/pip-install-lsy9asid/suds_55a5bbb1e4954c50bf56df351e6e7092/
Complete output (7 lines):
Traceback (most recent call last):
File "", line 1, in
File "/tmp/pip-install-lsy9asid/suds_55a5bbb1e4954c50bf56df351e6e7092/setup.py", line 20, in
import suds
File "/tmp/pip-install-lsy9asid/suds_55a5bbb1e4954c50bf56df351e6e7092/suds/init.py", line 154, in
import client
ModuleNotFoundError: No module named 'client'
----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/bc/d6/960acce47ee6f096345fe5a7d9be7708135fd1d0713571836f073efc7393/suds-0.4.tar.gz#sha256=d5524ae523bb9e09c57bcdbd1efae2c287d20603688ea31f6020ed180a489af0 (from https://pypi.org/simple/suds/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement suds==0.4 (from versions: 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.4)
ERROR: No matching distribution found for suds==0.4

**Comment by dipcb05** [comment]
i am trying to install onvif in my Django project.
it depends on suds.

i try to reinstall suds by pip, output -
Requirement already satisfied: suds in /home/dip05/anaconda3/lib/python3.7/site-packages (0.3.5)

how I can I solve it, and upgrade

**Comment by ThomasCr** [comment]
works only with python2

better try this fork https://github.com/FalkTannhaeuser/python-onvif-zeep

**Comment by FardadAnsari** [comment]
@ThomasCr Thanks for your reply. I was trying onvif-zeep for ptz controling

**Comment by FalkTannhaeuser** [comment]
@FardadAnsari You can try [python-onvif-zeep](https://github.com/FalkTannhaeuser/python-onvif-zeep) with Python3
