### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by sr-if** [quatanium/python-onvif#119]
Collecting onvif
  Downloading onvif-0.2.0.tar.gz (163 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.2/163.2 kB 1.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting suds>=0.4 (from onvif)
  Downloading suds-1.1.2-py3-none-any.whl (144 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 144.8/144.8 kB 1.6 MB/s eta 0:00:00
Collecting suds-passworddigest (from onvif)
  Downloading suds_passworddigest-0.1.2.zip (5.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-d65qqs9x/suds-passworddigest_43841844435b40dd8881c6abf0a5a19c/setup.py", line 18, in <module>
          long_description=file(
                           ^^^^
      NameError: name 'file' is not defined. Did you mean: 'filter'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by StuartIanNaylor** [comment]
Python 2.x (For a Python 3 compatible fork, see https://github.com/FalkTannhaeuser/python-onvif-zeep)
