### ISSUE TITLE
Latest version not functional anymore

### ISSUE THREAD

**Issue by elsampsa** [quatanium/python-onvif#13]
Hi,

Did a fresh install by downloading python-onvif with subversion and then running "sudo setup.py install".
When trying to use it, I get:
...
File "/usr/local/lib/python2.7/dist-packages/onvif-0.1.2-py2.7.egg/onvif/client.py", line 31, in wrapped
    raise ONVIFError(err)
onvif.exceptions.ONVIFError: Type not found: '(lang, http://www.w3.org/XML/1998/namespace, )'

Just a question .. have you tried the latest version yourself..? (from a fresh install)

**Comment by elsampsa** [comment]
Hi,

.. that bug was related to your recent changes in the .xsd files.  I was able to fix this.

Modify the file "bf-2.xsd" as follows: replace

schemaLocation="./addressing"

with

schemaLocation="./xml.xsd"

you must also add the correct and up-to-date schema file "xml.xsd" which can be fetched with

wget http://www.w3.org/2001/xml.xsd

Regards,
Sampsa

**Comment by Silex** [comment]
That fix doesn't work for me with an Axis P3354, I get this

```
onvif.exceptions.ONVIFError: Unknown error: (400, u'Bad Request')
```

**Comment by elsampsa** [comment]
That sounds like your camera does not support the onvif feature you are requesting..

Are you just trying to get the device management object or something else?  What onvif version your camera supports?

**Comment by Silex** [comment]
I was just trying to do `onvif-cli devicemgmt GetHostname`. The camera says it has version `Profile S`.

**Comment by guanche** [comment]
I followed the instruction written down by @elsampsa but with no luck. This library looks the most promising of the few I found, really hope there is a workaround/fix

My traceback
```
Traceback (most recent call last):
  File "/usr/local/bin/onvif-cli", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/onvif/cli.py", line 159, in main
    cli.setup(args)
  File "/usr/local/lib/python2.7/dist-packages/onvif/cli.py", line 38, in setup
    args.wsdl, encrypt=args.encrypt)
  File "/usr/local/lib/python2.7/dist-packages/onvif/client.py", line 216, in __init__
    self.update_xaddrs()
  File "/usr/local/lib/python2.7/dist-packages/onvif/client.py", line 222, in update_xaddrs
    self.devicemgmt  = self.create_devicemgmt_service()
  File "/usr/local/lib/python2.7/dist-packages/onvif/client.py", line 331, in create_devicemgmt_service
    return self.create_onvif_service('devicemgmt', from_template)
  File "/usr/local/lib/python2.7/dist-packages/onvif/client.py", line 319, in create_onvif_service
    self.daemon)
  File "/usr/local/lib/python2.7/dist-packages/onvif/client.py", line 28, in wrapped
    raise ONVIFError(err)
onvif.exceptions.ONVIFError: Type not found: '(lang, http://www.w3.org/XML/1998/namespace, )'
```

**Comment by pHaeusler** [comment]
It may be a problem with relative paths not working in suds. 

bf-2.xsd refers to "./xml.xsd".

It works if I use wsdl_dir explicitly:
`mycam = ONVIFCamera('192.168.0.11', 80, 'admin', 'password', wsdl_dir='/home/user/git/python-onvif/wsdl')`

The default of '/etc/onvif/wsdl/' fails

**Comment by texnofobix** [comment]
Motion / Sound sensors. 

for now I have the following 'hacked in' (pending on #https://github.com/quatanium/foscam-python-lib/pull/8). 

```bash
git clone https://github.com/texnofobix/foscam-python-lib.git 
chmod +x ./foscam-python-lib/foscmd
```
Then add the following:
```yaml
- platform: command_sensor
    name: foscam_motion
    command: './foscam-python-lib/foscmd -H 192.168.1.90 -P 88 -u texnofobix -p mypass'
    value_template: '{% if value_json.motionDetectAlarm == "0" %} disarm {% elif value_json.motionDetectAlarm == "1" %} off {% else %} on {% endif %}'
- platform: command_sensor
    name: foscam_sound
    command: './foscam-python-lib/foscmd -H 192.168.1.90 -P 88 -u texnofobix -p mypass'
    value_template: '{% if value_json.soundAlarm == "0" %} disarm {% elif value_json.soundAlarm == "1" %} off {% else %} on {% endif %}'
```
