### ISSUE TITLE
how to use the params

### ISSUE THREAD

**Issue by yuetianle** [quatanium/python-onvif#14]

**Comment by yuetianle** [comment]
cmd devicemgmt CreateUsers {'Username':'onvif_test','Password':'12345','UserLevel':Operator}

the error msg is
False: Invalid params
cmd devicemgmt CreateUsers {User:'Username':'onvif_test','Password':'12345','UserLevel':Operator}
the error msg is
Traceback (most recent call last):
  File "/usr/local/bin/onvif-cli", line 9, in <module>
    load_entry_point('onvif==0.1.2', 'console_scripts', 'onvif-cli')()
  File "/usr/local/lib/python2.7/dist-packages/onvif/cli.py", line 165, in main
    cli.cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/usr/local/lib/python2.7/dist-packages/onvif/cli.py", line 75, in do_cmd
    args.params = dict(literal_eval(match.group(1)))
  File "/usr/lib/python2.7/ast.py", line 49, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    {User:'Username':'onvif_test','Password':'12345','UserLevel':Operator}
                    ^
SyntaxError: invalid synta

anyone can help me

**Comment by yuetianle** [comment]
In python 
def add_user():
 31     mycam = ONVIFCamera('172.16.1.221', 80, 'admin', '12345')
 32     user_params = mycam.devicemgmt.create_type('CreateUsers')
 33     user_params.Username = 'onviftest'
 34     user_params.Password = '12345'
 35     user_params.UserLevel = 'Operator'
 36     mycam.devicemgmt.CreateUsers(user_params)                              
 37 add_user()

the error msg is 
Traceback (most recent call last):
  File "./test_python_onvif.py", line 37, in <module>
    add_user()
  File "./test_python_onvif.py", line 36, in add_user
    mycam.devicemgmt.CreateUsers(user_params)
  File "/usr/local/lib/python2.7/dist-packages/onvif/client.py", line 28, in wrapped
    raise ONVIFError(err)
onvif.exceptions.ONVIFError: the parameter value is illegal

**Comment by yuetianle** [comment]
in  python 
 def add_user():
 31     mycam = ONVIFCamera('172.16.1.221', 80, 'admin', '12345')
 32     user_params = mycam.devicemgmt.create_type('CreateUsers')
 33     user_params.Username = 'onviftest'
 34     user_params.Password = '12345'
 35     user_params.UserLevel = 'Operator'
 36     mycam.devicemgmt.CreateUsers({'User':{'Username':'onviftest1','Passwor#
 37 add_user()

add user ok
any one konw this issues, test hikvision camera.

**Comment by venkateshch141414** [comment]
is the problem solved???
