### ISSUE TITLE
events.py from examples doesn't work

### ISSUE THREAD

**Issue by vasvlad** [quatanium/python-onvif#15]
I tried to launch events.py for my camera, but I didn't have any success. :(

Traceback:
python events.py
[(Service){
Namespace = "http://www.onvif.org/ver10/device/wsdl"
XAddr = "http://10.0.0.38:80/onvif/device_service"
Version =
(OnvifVersion){
Major = 1
Minor = 3
}
}, (Service){
Namespace = "http://www.onvif.org/ver10/media/wsdl"
XAddr = "http://10.0.0.38:80/onvif/Media"
Version =
(OnvifVersion){
Major = 1
Minor = 3
}
}, (Service){
Namespace = "http://www.onvif.org/ver10/events/wsdl"
XAddr = "http://10.0.0.38:80/onvif/Events"
Version =
(OnvifVersion){
Major = 1
Minor = 4
}
}, (Service){
Namespace = "http://www.onvif.org/ver20/ptz/wsdl"
XAddr = "http://10.0.0.38:80/onvif/PTZ"
Version =
(OnvifVersion){
Major = 2
Minor = 1
}
}, (Service){
Namespace = "http://www.onvif.org/ver20/imaging/wsdl"
XAddr = "http://10.0.0.38:80/onvif/Imaging"
Version =
(OnvifVersion){
Major = 2
Minor = 1
}
}, (Service){
Namespace = "http://www.onvif.org/ver10/deviceIO/wsdl"
XAddr = "http://10.0.0.38:80/onvif/DeviceIO"
Version =
(OnvifVersion){
Major = 1
Minor = 1
}
}]
Traceback (most recent call last):
File "events.py", line 19, in
e_service = get_event_srv()
File "events.py", line 14, in get_event_srv
event_service = mycam.create_events_service()
File "/usr/local/lib/python2.7/dist-packages/onvif/client.py", line 360, in create_events_service
return self.create_onvif_service('events', from_template)
File "/usr/local/lib/python2.7/dist-packages/onvif/client.py", line 333, in create_onvif_service
self.daemon, no_cache=self.no_cache)
File "/usr/local/lib/python2.7/dist-packages/onvif/client.py", line 31, in wrapped
raise ONVIFError(err)
onvif.exceptions.ONVIFError: Unknown error: prefix (tds) not resolved

**Comment by vasvlad** [comment]
I've fixed this problem
See Pull request #16 
https://github.com/quatanium/python-onvif/pull/16
