### ISSUE TITLE
No services work (Unknown error: (400, u'Bad Request')) except from devicemgmt

### ISSUE THREAD

**Issue by tmlmt** [quatanium/python-onvif#19]
Hi guys,

Initializing an ONVIFCamera instance and a specific service goes smoothly, but I cannot get any service function to work appart from those of devicemgmt

My initialization script
```python
import onvif
camera = onvif.ONVIFCamera('192.168.1.108',80,'admin','<admin_password>')
# Create ptz service
camera_ptz = camera.create_ptz_service()
```

`camera.GetCapabilities()` works well and gives me for instance: 
```python
...
      PTZ = 
      (PTZCapabilities){
         XAddr = "http://192.168.1.108:80/onvif/ptz_service"
      }
...
```

But when I try one of camera_ptz' function, I get this : 
```python
>>> camera_ptz.GetStatus()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/onvif/client.py", line 28, in wrapped
    raise ONVIFError(err)
onvif.exceptions.ONVIFError: Unknown error: (400, u'Bad Request')
```

Using python 2.7.6 on a Raspberry Pi 2 running on Ubuntu 14.04.3, with modules onvif 0.1.2, suds 0.4 and suds-passworddigest 0.1.2 installed using pip.  

Any help would be appreciated! Thanks

**Comment by tmlmt** [comment]
Auto-solved, thanks to this post from Brad: http://sourceforge.net/p/onvifdm/discussion/1246119/thread/9a2a918a/

The author explains that the onvif user/password are actually different from the user/password to access the web interface of the camera (at least that's the case for the Dahua cameras that we both have). So trying with admin/admin worked ... 

He also suggests to use a piece of software like ODM (ONVIF Device Manager: http://sourceforge.net/projects/onvifdm/) to change/add onvif users. 

Too bad that the error returned (400 'Bad Request') is so vague. Is this due to the onvif specs or would it be possible to point the user towards the most likely error ('Wrong password' for instance)
