### ISSUE TITLE
onvif-cli throws error: onvif.exceptions.ONVIFError: Unknown error: ''

### ISSUE THREAD

**Issue by chklein** [quatanium/python-onvif#24]
pi@minibian:/home/DoorPI/doorpi$ onvif-cli devicemgmt GetHostname -u admin -a *****  --host '192.168.178.40' --port 554
Traceback (most recent call last):
  File "/usr/local/bin/onvif-cli", line 9, in <module>
    load_entry_point('onvif==0.1.2', 'console_scripts', 'onvif-cli')()
  File "/usr/local/lib/python2.7/dist-packages/onvif-0.1.2-py2.7.egg/onvif/cli.py", line 160, in main
    cli.setup(args)
  File "/usr/local/lib/python2.7/dist-packages/onvif-0.1.2-py2.7.egg/onvif/cli.py", line 39, in setup
    args.wsdl, encrypt=args.encrypt)
  File "/usr/local/lib/python2.7/dist-packages/onvif-0.1.2-py2.7.egg/onvif/client.py", line 227, in __init__
    self.update_xaddrs()
  File "/usr/local/lib/python2.7/dist-packages/onvif-0.1.2-py2.7.egg/onvif/client.py", line 237, in update_xaddrs
    services = self.devicemgmt.GetServices({'IncludeCapability': False})
  File "/usr/local/lib/python2.7/dist-packages/onvif-0.1.2-py2.7.egg/onvif/client.py", line 31, in wrapped
    raise ONVIFError(err)
onvif.exceptions.ONVIFError: Unknown error: ''

I really don't know what to do...please help

**Comment by chklein** [comment]
Solved.

It was the wrong --port. The right value was 2000, igot it from graphical ONVIF Device Manager for Windows.
