### ISSUE TITLE
SOAP version mismatch

### ISSUE THREAD

**Issue by tangb** [quatanium/python-onvif#3]
Hi

I'm using onvif lib to control Axis camera and I always got "SOAP version mismatch" exception.
It seems device doesnt support sent SOAP data.
Is there a way to debug onvif lib (logging?) to get real SOAP request sent to the device?

My code is working well on chinese devices.

Thx for support.

Tangb

**Comment by tangb** [comment]
Hi

Here is the SOAP request:
```
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns0="http://www.onvif.org/ver10/device/wsdl" xmlns:ns1="http://schemas.xmlsoap.org/soap/envelope/" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <SOAP-ENV:Header>
      <wsse:Security mustUnderstand="true">
         <wsse:UsernameToken>
            <wsse:Username>mylogin</wsse:Username>
            <wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">i89/K6D<...>l2cnp4=</wsse:Password>
            <wsse:Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">YWExMDR<...>zUzMGUyYjkwYzAyNTY=</wsse:Nonce>
            <wsu:Created>2015-05-07T12:00:19.116062Z</wsu:Created>
         </wsse:UsernameToken>
      </wsse:Security>
   </SOAP-ENV:Header>
   <ns1:Body>
      <ns0:GetServices>
         <ns0:IncludeCapability>false</ns0:IncludeCapability>
      </ns0:GetServices>
   </ns1:Body>
</SOAP-ENV:Envelope>
```

and the SOAP response:
```
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:aa="http://www.axis.com/vapix/ws/action1" xmlns:acert="http://www.axis.com/vapix/ws/cert" xmlns:acertificates="http://www.axis.com/vapix/ws/certificates" xmlns:aev="http://www.axis.com/vapix/ws/event1" xmlns:ali="http://www.axis.com/vapix/ws/light" xmlns:ali1="http://www.axis.com/vapix/ws/light/CommonBinding" xmlns:ali2="http://www.axis.com/vapix/ws/light/IntensityBinding" xmlns:ali3="http://www.axis.com/vapix/ws/light/AngleOfIlluminationBinding" xmlns:ali4="http://www.axis.com/vapix/ws/light/DayNightSynchronizeBinding" xmlns:apc="http://www.axis.com/vapix/ws/panopsiscalibration1" xmlns:arth="http://www.axis.com/vapix/ws/recordedtour1" xmlns:aweb="http://www.axis.com/vapix/ws/webserver" xmlns:c14n="http://www.w3.org/2001/10/xml-exc-c14n#" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:tan="http://www.onvif.org/ver20/analytics/wsdl" xmlns:tan1="http://www.onvif.org/ver20/analytics/wsdl/RuleEngineBinding" xmlns:tan2="http://www.onvif.org/ver20/analytics/wsdl/AnalyticsEngineBinding" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:ter="http://www.onvif.org/ver10/error" xmlns:tev="http://www.onvif.org/ver10/events/wsdl" xmlns:tev1="http://www.onvif.org/ver10/events/wsdl/NotificationProducerBinding" xmlns:tev2="http://www.onvif.org/ver10/events/wsdl/EventBinding" xmlns:tev3="http://www.onvif.org/ver10/events/wsdl/SubscriptionManagerBinding" xmlns:tev4="http://www.onvif.org/ver10/events/wsdl/PullPointSubscriptionBinding" xmlns:timg="http://www.onvif.org/ver20/imaging/wsdl" xmlns:tns1="http://www.onvif.org/ver10/topics" xmlns:tnsaxis="http://www.axis.com/2009/event/topics" xmlns:tptz="http://www.onvif.org/ver20/ptz/wsdl" xmlns:trt="http://www.onvif.org/ver10/media/wsdl" xmlns:tt="http://www.onvif.org/ver10/schema" xmlns:wsa5="http://www.w3.org/2005/08/addressing" xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2" xmlns:wsrfbf="http://docs.oasis-open.org/wsrf/bf-2" xmlns:wsrfr="http://docs.oasis-open.org/wsrf/r-2" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wstop="http://docs.oasis-open.org/wsn/t-1" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xmime="http://tempuri.org/xmime.xsd" xmlns:xop="http://www.w3.org/2004/08/xop/include" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <SOAP-ENV:Body>
      <SOAP-ENV:Fault SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
         <SOAP-ENV:Code>
            <SOAP-ENV:Value>env:VersionMismatch</SOAP-ENV:Value>
         </SOAP-ENV:Code>
         <SOAP-ENV:Reason>
            <SOAP-ENV:Text xml:lang="en">SOAP version mismatch</SOAP-ENV:Text>
         </SOAP-ENV:Reason>
         <SOAP-ENV:Detail>
            <SOAP-ENV:Text>Invalid SOAP message or SOAP version mismatch</SOAP-ENV:Text>
         </SOAP-ENV:Detail>
      </SOAP-ENV:Fault>
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

Maybe expert eyes can find a clue :S
Taking a look at onvif specs http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0.pdf , all seems good.

Any help will be really appreciated ;)
Thx.

**Comment by semirturgay** [comment]
i have got same error. did you found any solution

**Comment by sinchb** [comment]
@tangb  @semirturgay  sorry for late response.  I haven't an Axis camera to test. Does [this](http://sourceforge.net/projects/onvifdm/) tool work fine for your camera?

**Comment by semirturgay** [comment]
@sinchb never mind. I tested the program now it works for me.

**Comment by tangb** [comment]
Hi

Thx for your reply

I can't run application you mentionned, I'm running linux and mac only.
But the android app onvifer https://play.google.com/store/apps/details?id=net.biyee.onvifer is working well.

**Comment by sinchb** [comment]
@semirturgay  Thanks for your report. :)

**Comment by sinchb** [comment]
@tangb what is your camera model ? Can you paste something more, for example, the SOAP request and the response ?

**Comment by flyingpang** [comment]
@sinchb I clone the repository and run setup.py,but it has a bunch of error.how I solve it? I don't know  how to copy from git,so I copied it by pycharm.
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "C:\Users\flyingpang\AppData\Local\Temp\pycharm-packaging5050050075764247939.tmp\onvif\setup.py", line 49, in <module>

    'console_scripts': ['onvif-cli = onvif.cli:main']

  File "C:\Python27\lib\distutils\core.py", line 151, in setup

    dist.run_commands()

  File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command

    cmd_obj.run()

  File "build\bdist.win-amd64\egg\setuptools\command\install.py", line 53, in run

  File "C:\Python27\lib\distutils\command\install.py", line 575, in run

    self.run_command(cmd_name)

  File "C:\Python27\lib\distutils\cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command

    cmd_obj.run()

  File "C:\Python27\lib\distutils\command\install_data.py", line 58, in run

    dir = convert_path(f[0])

  File "C:\Python27\lib\distutils\util.py", line 124, in convert_path

    raise ValueError, "path '%s' cannot be absolute" % pathname

ValueError: path '/etc/onvif/wsdl' cannot be absolute

**Comment by sinchb** [comment]
@flyingpang python-onvif doesn't support windows now. The path '/etc/onvif/wsdl' is for unix only. There is a temporary solution.

replace this line in setup.py

```python
data_files=[('/etc/onvif/wsdl', wsdl_files)] 
```

with this:

```python
 data_files=[('./wsdl', wsdl_files)]"
```

this **maybe** works...

**Comment by semirturgay** [comment]
@sinchb  did you make progress on **soap mismatch** issue ? 
thanks.

**Comment by tangb** [comment]
@semirturgay I guess he needs some data to do something :-)
I will try to give some samples asap.
Maybe @semirturgay you can give him some too ?

**Comment by sinchb** [comment]
@tangb @semirturgay  well, I guess that someting about python-onvif wsse is wrong. Please execute the following script and give me the result. Thanks :)
```python
import requests
request_xml = '''
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns0="http://www.onvif.org/ver10/device/wsdl" xmlns:ns1="http://schemas.xmlsoap.org/soap/envelope/" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <ns1:Body>
      <ns0:GetServices>
         <ns0:IncludeCapability>false</ns0:IncludeCapability>
      </ns0:GetServices>
   </ns1:Body>
</SOAP-ENV:Envelope>
'''
import httplib
ip = 'camip:camPort'
path="/onvif/device_service"
conn = httplib.HTTPConnection(ip)
conn.request("POST", path, request_xml)
resp = conn.getresponse().read()
print resp
```

**Comment by tangb** [comment]
@sinchb:
Same problem "SOAP version mismatch"
http://pastebin.com/mxnegbYM

**Comment by semirturgay** [comment]
i run the script i get the following response : 

   

     <?xml version="1.0" encoding="UTF-8"?>
        <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:c14n="http://www.w3.org/2001/10/xml-exc-c14n#" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsa5="http://www.w3.org/2005/08/addressing" xmlns:xmime5="http://www.w3.org/2005/05/xmlmime" xmlns:wsrf-bf="http://docs.oasis-open.org/wsrf/bf-2" xmlns:wstop="http://docs.oasis-open.org/wsn/t-1" xmlns:tt="http://www.onvif.org/ver10/schema" xmlns:wsrf-r="http://docs.oasis-open.org/wsrf/r-2" xmlns:tan1="http://www.onvif.org/ver10/analytics/wsdl/RuleEngineBinding" xmlns:tan="http://www.onvif.org/ver10/analytics/wsdl" xmlns:tan2="http://www.onvif.org/ver10/analytics/wsdl/AnalyticsEngineBinding" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:tev1="http://www.onvif.org/ver10/events/wsdl/NotificationProducerBinding" xmlns:tev2="http://www.onvif.org/ver10/events/wsdl/EventBinding" xmlns:tev3="http://www.onvif.org/ver10/events/wsdl/SubscriptionManagerBinding" xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2" xmlns:tev4="http://www.onvif.org/ver10/events/wsdl/PullPointSubscriptionBinding" xmlns:tev="http://www.onvif.org/ver10/events/wsdl" xmlns:timg="http://www.onvif.org/ver10/imaging/wsdl" xmlns:tptz="http://www.onvif.org/ver10/ptz/wsdl" xmlns:trt="http://www.onvif.org/ver10/media/wsdl" xmlns:ter="http://www.onvif.org/ver10/error" xmlns:tns1="http://www.onvif.org/ver10/topics" xmlns:tnsaxis="http://www.axis.com/2009/event/topics"><SOAP-ENV:Body><SOAP-ENV:Fault SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><SOAP-ENV:Code><SOAP-ENV:Value>env:VersionMismatch</SOAP-ENV:Value></SOAP-ENV:Code><SOAP-ENV:Reason><SOAP-ENV:Text xml:lang="en">SOAP version mismatch</SOAP-ENV:Text></SOAP-ENV:Reason><SOAP-ENV:Detail><SOAP-ENV:Text>Invalid SOAP message or SOAP version mismatch</SOAP-ENV:Text></SOAP-ENV:Detail></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>

**Comment by sinchb** [comment]
@tangb @semirturgay OK, thank you. I wonder something is wrong about suds. Would you have another test? Please try [this](https://github.com/Pegax/pyOnvif/blob/master/pyonvif.py) lib, and paste the response of  ```getServices ```.

**Comment by tangb** [comment]
@sinchb 

Using pyonvif lib:

>>> import pyonvif
>>> axis = pyonvif.OnvifCam()
>>> axis.setup(False,'<ip>', '/onvif/device_service')
True
>>> axis.setAuth('<login>', '<pwd>')
>>> axis.getServices()
'<?xml version="1.0" encoding="UTF-8"?>\n<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:c14n="http://www.w3.org/2001/10/xml-exc-c14n#" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsa5="http://www.w3.org/2005/08/addressing" xmlns:xmime="http://tempuri.org/xmime.xsd" xmlns:xop="http://www.w3.org/2004/08/xop/include" xmlns:wsrfbf="http://docs.oasis-open.org/wsrf/bf-2" xmlns:wstop="http://docs.oasis-open.org/wsn/t-1" xmlns:tt="http://www.onvif.org/ver10/schema" xmlns:acert="http://www.axis.com/vapix/ws/cert" xmlns:wsrfr="http://docs.oasis-open.org/wsrf/r-2" xmlns:aa="http://www.axis.com/vapix/ws/action1" xmlns:acertificates="http://www.axis.com/vapix/ws/certificates" xmlns:aev="http://www.axis.com/vapix/ws/event1" xmlns:ali1="http://www.axis.com/vapix/ws/light/CommonBinding" xmlns:ali2="http://www.axis.com/vapix/ws/light/IntensityBinding" xmlns:ali3="http://www.axis.com/vapix/ws/light/AngleOfIlluminationBinding" xmlns:ali4="http://www.axis.com/vapix/ws/light/DayNightSynchronizeBinding" xmlns:ali="http://www.axis.com/vapix/ws/light" xmlns:apc="http://www.axis.com/vapix/ws/panopsiscalibration1" xmlns:arth="http://www.axis.com/vapix/ws/recordedtour1" xmlns:aweb="http://www.axis.com/vapix/ws/webserver" xmlns:tan1="http://www.onvif.org/ver20/analytics/wsdl/RuleEngineBinding" xmlns:tan2="http://www.onvif.org/ver20/analytics/wsdl/AnalyticsEngineBinding" xmlns:tan="http://www.onvif.org/ver20/analytics/wsdl" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:tev1="http://www.onvif.org/ver10/events/wsdl/NotificationProducerBinding" xmlns:tev2="http://www.onvif.org/ver10/events/wsdl/EventBinding" xmlns:tev3="http://www.onvif.org/ver10/events/wsdl/SubscriptionManagerBinding" xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2" xmlns:tev4="http://www.onvif.org/ver10/events/wsdl/PullPointSubscriptionBinding" xmlns:tev="http://www.onvif.org/ver10/events/wsdl" xmlns:timg="http://www.onvif.org/ver20/imaging/wsdl" xmlns:tptz="http://www.onvif.org/ver20/ptz/wsdl" xmlns:trt="http://www.onvif.org/ver10/media/wsdl" xmlns:ter="http://www.onvif.org/ver10/error" xmlns:tns1="http://www.onvif.org/ver10/topics" xmlns:tnsaxis="http://www.axis.com/2009/event/topics"><SOAP-ENV:Header></SOAP-ENV:Header><SOAP-ENV:Body><SOAP-ENV:Fault SOAP-ENV:encodingStyle="http://www.w3.org/2003/05/soap-encoding"><SOAP-ENV:Code><SOAP-ENV:Value>SOAP-ENV:Receiver</SOAP-ENV:Value><SOAP-ENV:Subcode><SOAP-ENV:Value>ter:Action</SOAP-ENV:Value></SOAP-ENV:Subcode></SOAP-ENV:Code><SOAP-ENV:Reason><SOAP-ENV:Text xml:lang="en">Action failed</SOAP-ENV:Text></SOAP-ENV:Reason><SOAP-ENV:Detail><SOAP-ENV:Text>The requested SOAP action failed</SOAP-ENV:Text></SOAP-ENV:Detail></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>'

WSDiscovery doens't find the axis cam. I forced parameters.

**Comment by semirturgay** [comment]
WSDiscovery doesn't find my cam too.

**Comment by semirturgay** [comment]
@sinchb  i tried to connect to cam with only using suds as follow : 
```
import suds
import os
 
SERVICE_URL = 'http://xx.x.xx.xxx:80/onvif/device_service'
WSDL_URL='file:' + os.getcwd() + '/wsdl/devicemgmt.wsdl'
client=suds.client.Client(WSDL_URL, faults=False)
client.set_options(location=SERVICE_URL)
security =  suds.wsse.Security()
token =  suds.wsse.UsernameToken('xxx', 'xxxx')
token.setcreated()
security.tokens.append(token)
res=client.service.GetCertificatesStatus()
print res
```

it gives this error:
```
Traceback (most recent call last):
  File "test2.py", line 14, in <module>
    res=client.service.GetCertificatesStatus()
  File "/Library/Python/2.7/site-packages/suds/client.py", line 538, in __call__
    return client.invoke(args, kwargs)
  File "/Library/Python/2.7/site-packages/suds/client.py", line 602, in invoke
    result = self.send(soapenv)
  File "/Library/Python/2.7/site-packages/suds/client.py", line 649, in send
    result = self.failed(binding, e)
  File "/Library/Python/2.7/site-packages/suds/client.py", line 702, in failed
    r, p = binding.get_fault(reply)
  File "/Library/Python/2.7/site-packages/suds/bindings/binding.py", line 266, in get_fault
    return (faultroot, p.detail)
AttributeError: Fault instance has no attribute 'detail'
```

**Comment by tangb** [comment]
I tested the same code:
```
>>>import suds
>>>import logging
>>>logging.basicConfig(level=logging.INFO)
>>>logging.getLogger('suds.client').setLevel(logging.DEBUG)
>>>SERVICE_URL = 'http://<ip>:80/onvif/device_service'
>>>WSDL_URL='file:/etc/onvif/wsdl/devicemgmt.wsdl'
>>>client=suds.client.Client(WSDL_URL, faults=True)
>>>client.set_options(location=SERVICE_URL)
>>>client.service.GetCertificatesStatus()
DEBUG:suds.client:sending to (http://192.168.168.125:80/onvif/device_service)
message:
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:ns0="http://www.onvif.org/ver10/device/wsdl" xmlns:ns1="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
   <SOAP-ENV:Header/>
   <ns1:Body>
      <ns0:GetCertificatesStatus/>
   </ns1:Body>
</SOAP-ENV:Envelope>
DEBUG:suds.client:headers = {'SOAPAction': '"http://www.onvif.org/ver10/device/wsdl/GetCertificatesStatus"', 'Content-Type': 'text/xml; charset=utf-8'}
ERROR:suds.client:<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:ns0="http://www.onvif.org/ver10/device/wsdl" xmlns:ns1="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
   <SOAP-ENV:Header/>
   <ns1:Body>
      <ns0:GetCertificatesStatus/>
   </ns1:Body>
</SOAP-ENV:Envelope>
DEBUG:suds.client:http failed:
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:c14n="http://www.w3.org/2001/10/xml-exc-c14n#" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsa5="http://www.w3.org/2005/08/addressing" xmlns:xmime="http://tempuri.org/xmime.xsd" xmlns:xop="http://www.w3.org/2004/08/xop/include" xmlns:wsrfbf="http://docs.oasis-open.org/wsrf/bf-2" xmlns:wstop="http://docs.oasis-open.org/wsn/t-1" xmlns:tt="http://www.onvif.org/ver10/schema" xmlns:acert="http://www.axis.com/vapix/ws/cert" xmlns:wsrfr="http://docs.oasis-open.org/wsrf/r-2" xmlns:aa="http://www.axis.com/vapix/ws/action1" xmlns:acertificates="http://www.axis.com/vapix/ws/certificates" xmlns:aev="http://www.axis.com/vapix/ws/event1" xmlns:ali1="http://www.axis.com/vapix/ws/light/CommonBinding" xmlns:ali2="http://www.axis.com/vapix/ws/light/IntensityBinding" xmlns:ali3="http://www.axis.com/vapix/ws/light/AngleOfIlluminationBinding" xmlns:ali4="http://www.axis.com/vapix/ws/light/DayNightSynchronizeBinding" xmlns:ali="http://www.axis.com/vapix/ws/light" xmlns:apc="http://www.axis.com/vapix/ws/panopsiscalibration1" xmlns:arth="http://www.axis.com/vapix/ws/recordedtour1" xmlns:aweb="http://www.axis.com/vapix/ws/webserver" xmlns:tan1="http://www.onvif.org/ver20/analytics/wsdl/RuleEngineBinding" xmlns:tan2="http://www.onvif.org/ver20/analytics/wsdl/AnalyticsEngineBinding" xmlns:tan="http://www.onvif.org/ver20/analytics/wsdl" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:tev1="http://www.onvif.org/ver10/events/wsdl/NotificationProducerBinding" xmlns:tev2="http://www.onvif.org/ver10/events/wsdl/EventBinding" xmlns:tev3="http://www.onvif.org/ver10/events/wsdl/SubscriptionManagerBinding" xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2" xmlns:tev4="http://www.onvif.org/ver10/events/wsdl/PullPointSubscriptionBinding" xmlns:tev="http://www.onvif.org/ver10/events/wsdl" xmlns:timg="http://www.onvif.org/ver20/imaging/wsdl" xmlns:tptz="http://www.onvif.org/ver20/ptz/wsdl" xmlns:trt="http://www.onvif.org/ver10/media/wsdl" xmlns:ter="http://www.onvif.org/ver10/error" xmlns:tns1="http://www.onvif.org/ver10/topics" xmlns:tnsaxis="http://www.axis.com/2009/event/topics"><SOAP-ENV:Body><SOAP-ENV:Fault SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><SOAP-ENV:Code><SOAP-ENV:Value>env:VersionMismatch</SOAP-ENV:Value></SOAP-ENV:Code><SOAP-ENV:Reason><SOAP-ENV:Text xml:lang="en">SOAP version mismatch</SOAP-ENV:Text></SOAP-ENV:Reason><SOAP-ENV:Detail><SOAP-ENV:Text>Invalid SOAP message or SOAP version mismatch</SOAP-ENV:Text></SOAP-ENV:Detail></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/suds/client.py", line 542, in __call__
    return client.invoke(args, kwargs)
  File "/usr/lib/python2.7/dist-packages/suds/client.py", line 602, in invoke
    result = self.send(soapenv)
  File "/usr/lib/python2.7/dist-packages/suds/client.py", line 653, in send
    result = self.failed(binding, e)
  File "/usr/lib/python2.7/dist-packages/suds/client.py", line 708, in failed
    r, p = binding.get_fault(reply)
  File "/usr/lib/python2.7/dist-packages/suds/bindings/binding.py", line 265, in get_fault
    raise WebFault(p, faultroot)
suds.WebFault
```

SOAP version mismatch. I guess it confirms it is a suds problem.

**Comment by semirturgay** [comment]
@tangb yes i was think the problem is related with suds.  so what is next ?

**Comment by flyingpang** [comment]
@sinchb I test  examples in examples folder and test.py in the tests folder today,but these didn't work.I open my the  local address 192.168.0.112 in brower. I run in ubuntu(desktop14.4.2).
Traceback (most recent call last):
  File "continuous_move.py", line 83, in <module>
    continuous_move()
  File "continuous_move.py", line 43, in continuous_move
    mycam = ONVIFCamera('192.168.0.112', 80, 'admin', '12345')
  File "/usr/local/lib/python2.7/dist-packages/onvif-0.1.2-py2.7.egg/onvif/client.py", line 216, in __init__
    self.update_xaddrs()
  File "/usr/local/lib/python2.7/dist-packages/onvif-0.1.2-py2.7.egg/onvif/client.py", line 226, in update_xaddrs
    services = self.devicemgmt.GetServices({'IncludeCapability': False})
  File "/usr/local/lib/python2.7/dist-packages/onvif-0.1.2-py2.7.egg/onvif/client.py", line 28, in wrapped
    raise ONVIFError(err)
onvif.exceptions.ONVIFError: Unknown error: <urlopen error timed out>

**Comment by flyingpang** [comment]
@sinchb onvif.exceptions.ONVIFError: Unknown error: <urlopen error timed out>

**Comment by flyingpang** [comment]
@sinchb the error displays urlopen error time out,I copied,but the comment didn't show.

**Comment by taiyangc** [comment]
@flyingpang Please open a new issue on this error, thanks.

**Comment by tangb** [comment]
I have some better results replacing in suds/bindings/binding.py ~line38:
this:
```
envns = ('SOAP-ENV', 'http://schemas.xmlsoap.org/soap/envelope/')
```
by this:
```
envns = ('SOAP-ENV', 'http://www.w3.org/2003/05/soap-envelope')
```

It doesn't say "SOAP version mismatch" but "Bad request ... NotAuthorized..."

**Comment by flyingpang** [comment]
@taiyangc sorry.I open a new issue about this error.

**Comment by flyingpang** [comment]
@taiyangc sorry.I open a new issue about this error.

**Comment by semirturgay** [comment]
@tangb  it worked for me when i change the envs variable like you said in binding.py

**Comment by semirturgay** [comment]
@tangb  by the way did you enabled web servises for your camera ?

**Comment by tangb** [comment]
@semirturgay nope i don't
It always returns "action failed"

**Comment by semirturgay** [comment]
@tangb you use axis I guess can you check this https://www.youtube.com/watch?v=UinkTCmW_Rs

**Comment by tangb** [comment]
onvif is enabled, it works with an onvif android app

**Comment by sinchb** [comment]
@tangb  @semirturgay How about [this](https://bitbucket.org/jurko/suds) one? It forked from suds and keep up to date.

**Comment by tangb** [comment]
@sinchb: already tryed and same issue.

**Comment by sinchb** [comment]
@tangb please try other [soap clients](http://stackoverflow.com/questions/206154/what-soap-client-libraries-exist-for-python-and-where-is-the-documentation-for).

**Comment by tangb** [comment]
@sinchb
Here is my results:
* **SOAPy:** completely outdated. I'm running python 2.7 and it supports until 2.5.
* **ZSI:** not tested
* **SUDS:** problems we know
* **spyne:** only support soap v1.1. Camera is soap v1.2
* **ladon:** only soap v1.1
* **pysimplesoap:** try a lot to understand how it works. But it doesn't do the job. Generated soap is not valid for onvif request (it appears). 
* **SOAPpy:** discontinued, They recommand to use SUDS
* **soaplib:** client part is done using SUDS
* **osa:** I didn't find a way to connect to camera.

**Comment by taiyangc** [comment]
@tangb Would it be possible to email @sinchb or me a public login address for your camera? That would  greatly expedite debugging for both of us.

**Comment by Silex** [comment]
I also have this problem on an Axis P3354

**Comment by jaeger4** [comment]
@taiyangc @sinchb I can provide you public access to a Axis M1034-W - I sent you an email on 17.9.

**Comment by jscott1644** [comment]
9d67718ac118b989e2d45afaf075eec8456d48ef seems to resolve this issue. I am able to talk to Axis cameras, which reject anything but SOAP 1.2 envelope.
