### ISSUE TITLE
Create recording service fail

### ISSUE THREAD

**Issue by plegal** [quatanium/python-onvif#33]
Hi,
Thanks for your work.
I try to create an recording service with :+1: 

self.recording = self.speedcam.create_recording_service()

I got this error : Unknown error: binding 'trc:DeviceBinding', not-found

Anyone test this function ?

Thx

Philippe

**Comment by 123xiangfei** [comment]
Hi,
I also have question like you . Are you solved? Please tell me how to do it. 

I run this:
# -*- coding: utf-8 -*-
from onvif import ONVIFCamera, ONVIFService
__author__ = 'vahid'

if __name__ == '__main__':

    device_service = ONVIFService('http://192.167.0.4:80/onvif/device_service', 'TEST', 'hjdz1234', 'D:/Python27/Lib/site-packages/onvif-0.2.0-py2.7.egg/wsdl/devicemgmt.wsdl')
    resp = device_service.devicemgmt.GetCapabilities()
    print resp

return  result:
D:\Python27\python.exe C:/Users/Administrator/python-onvif-master/examples/recording.py
Traceback (most recent call last):
  File "C:/Users/Administrator/python-onvif-master/examples/recording.py", line 9, in <module>
    resp = device_service.devicemgmt.GetCapabilities()
  File "C:\Users\Administrator\python-onvif-master\onvif\client.py", line 212, in __getattr__
    return self.service_wrapper(getattr(self.ws_client.service, name))
  File "build\bdist.win-amd64\egg\suds\client.py", line 299, in __getattr__
  File "build\bdist.win-amd64\egg\suds\client.py", line 403, in __getattr__
  File "build\bdist.win-amd64\egg\suds\client.py", line 494, in __getattr__
  File "build\bdist.win-amd64\egg\suds\client.py", line 507, in __getitem__
suds.MethodNotFound: Method not found: 'DeviceService.DevicePort.devicemgmt'

Process finished with exit code 1

any idea?

Thx

allmu

**Comment by venkateshch141414** [comment]
Hi,
is issue solved?
mycam = ONVIFCamera('192.168.1.1',80,'admin','admin', '/home/venky/Desktop/wsdl/') 
recording_service = mycam.create_recording_service()
it gives an error that Device Does not support recording but in camera spec it is saying that it supports profile G. any idea??

Thanks
Venkatesh

**Comment by chinmay-d** [comment]
Does it have any fix yet?  I am also getting this error even though my camera supports recording.

Error:
`onvif.exceptions.ONVIFError: Unknown error: Device doesn't support service: recording`
Please post here if anyone has found the fix....

thanks :)
