### ISSUE TITLE
NoneType' object has no attribute 'promotePrefixes' error when calling openvif-cli

### ISSUE THREAD

**Issue by biinster** [quatanium/python-onvif#36]
onvif-cli -u "admin" -a "..." --host "192.168.100.3" --port 80 --wsdl /usr/local/wsdl/
Traceback (most recent call last):
  File "/usr/local/bin/onvif-cli", line 9, in <module>
    load_entry_point('onvif==0.1.3', 'console_scripts', 'onvif-cli')()
  File "/usr/local/lib/python2.7/dist-packages/onvif/cli.py", line 160, in main
    cli.setup(args)
  File "/usr/local/lib/python2.7/dist-packages/onvif/cli.py", line 39, in setup
    args.wsdl, encrypt=args.encrypt)
  File "/usr/local/lib/python2.7/dist-packages/onvif/client.py", line 227, in __init__
    self.update_xaddrs()
  File "/usr/local/lib/python2.7/dist-packages/onvif/client.py", line 237, in update_xaddrs
    services = self.devicemgmt.GetServices({'IncludeCapability': False})
  File "/usr/local/lib/python2.7/dist-packages/onvif/client.py", line 31, in wrapped
    raise ONVIFError(err)
onvif.exceptions.ONVIFError: Unknown error: 'NoneType' object has no attribute 'promotePrefixes'

Has anyone ever had this problem?

**Comment by jogu** [comment]
I have the same issue. Latest git master against an sv3c b01-4mp-poe camera.

**Comment by jogu** [comment]
For my case, the issue is that the http server that supports onvif is not on port 80 - it works once I added `--port 8899`.
