### ISSUE TITLE
Method 'SOAP-ENV:Envelope' not implemented with Avigilon 2.0W-H3-BO1-IR

### ISSUE THREAD

**Issue by xanview** [quatanium/python-onvif#42]
I'm using version 0.1.3, when I try to run onvif-cli in interactive mode, or request anything else like GetDeviceInformation, I'm getting the following:

```
$ .local/bin/onvif-cli -u admin -a admin --host '192.168.0.3' --port 80
Traceback (most recent call last):
  File ".local/bin/onvif-cli", line 11, in <module>
    sys.exit(main())
  File "/home/deployer/.local/lib/python2.7/site-packages/onvif/cli.py", line 160, in main
    cli.setup(args)
  File "/home/deployer/.local/lib/python2.7/site-packages/onvif/cli.py", line 39, in setup
    args.wsdl, encrypt=args.encrypt)
  File "/home/deployer/.local/lib/python2.7/site-packages/onvif/client.py", line 227, in __init__
    self.update_xaddrs()
  File "/home/deployer/.local/lib/python2.7/site-packages/onvif/client.py", line 237, in update_xaddrs
    services = self.devicemgmt.GetServices({'IncludeCapability': False})
  File "/home/deployer/.local/lib/python2.7/site-packages/onvif/client.py", line 31, in wrapped
    raise ONVIFError(err)
onvif.exceptions.ONVIFError: Unknown error: (400, u'Bad Request')
```

The camera in ONVIF Compliance: v1.02, v2.00, Profile S. I'm running the latest firmware and the time on the camera is correct.

Any ideas?

**Comment by xanview** [comment]
Just to confirm, it works with ODM:

![screen shot 2016-09-16 at 20 17 01](https://cloud.githubusercontent.com/assets/578881/18598434/a27f427e-7c4a-11e6-87a3-0307e3487f14.jpg)

**Comment by xanview** [comment]
If I look at the logs on the camera, it says this when I run the command above:

```
W(t101:CameraApp:2.6.0.100:13760) [353538(1038) 2016-09-16T19:21:45.652Z] "Soap fault <code>SOAP-ENV:Sender</code><reason>Method 'SOAP-ENV:Envelope' not implemented: method name or namespace not recognized</reason>: 192.168.0.3 - ns0:GetServices (admin)"
```

**Comment by xanview** [comment]
Here is screenshot from ONVIF Device Test Tool:
![screen shot 2016-09-16 at 20 49 29](https://cloud.githubusercontent.com/assets/578881/18599233/2edde1cc-7c4f-11e6-9474-fc73d9aa0fa1.jpg)

**Comment by xanview** [comment]
I noticed in the official onvif tool, certain requests don't work with the "Digest" authentication method, but they do with the "WS-Username token".

**Comment by xanview** [comment]
This seems to be fixed in latest trunk! - Could you please make a release :)

```
>>> camera = ONVIFCamera('192.168.0.3', 80, 'admin', 'admin')
>>> camera.devicemgmt.GetHostname()
(HostnameInformation){
   FromDHCP = False
   Name = "C5-0-H3-BO2-IR-13346619.AVIGILON"
 }
```
