### ISSUE TITLE
Unknown error: <unknown>:1:2585: not well-formed (invalid token)

### ISSUE THREAD

**Issue by tringler** [quatanium/python-onvif#48]
Hello,

can anyone help me how I can get rid of this problem? Onvif implementation on the device should be ok, because [ONVIF Device Manager](https://sourceforge.net/projects/onvifdm/) is working.

Thanks in Advance!

```
root@ubuntu:~/.homeassistant/custom_components/camera/test# onvif-cli -u 'admin-user' -a 'admin-password' --host '10.10.10.10' --port 10080 --wsdl /usr/local/wsdl/
Traceback (most recent call last):
  File "/usr/local/bin/onvif-cli", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/onvif/cli.py", line 160, in main
    cli.setup(args)
  File "/usr/local/lib/python2.7/dist-packages/onvif/cli.py", line 39, in setup
    args.wsdl, encrypt=args.encrypt)
  File "/usr/local/lib/python2.7/dist-packages/onvif/client.py", line 227, in __init__
    self.update_xaddrs()
  File "/usr/local/lib/python2.7/dist-packages/onvif/client.py", line 237, in update_xaddrs
    services = self.devicemgmt.GetServices({'IncludeCapability': False})
  File "/usr/local/lib/python2.7/dist-packages/onvif/client.py", line 31, in wrapped
    raise ONVIFError(err)
onvif.exceptions.ONVIFError: Unknown error: <unknown>:1:2585: not well-formed (invalid token)
```

**Comment by tringler** [comment]
Sorry. Indeed there seems to be an malformed XML by my device, which is however ignored by [ONVIF Device Manager](https://sourceforge.net/projects/onvifdm/)

```
</tds:GetServicesResponse</s:Body></s:Envelope>
```
