### ISSUE TITLE
[b50e7b1]onvif.exceptions.ONVIFError: Unknown error: <urlopen error [Errno 61] Connection refused>

### ISSUE THREAD

**Issue by liuxue0905** [quatanium/python-onvif#51]
Version:
Latest commit b50e7b1  28 days ago

[b50e7b1]This version catch more exceptions that older version never shown.

Error:
Traceback (most recent call last):
  File "/Users/liuxue/PycharmProjects/MyProject/odm/TONVIF.py", line 5, in <module>
    camera = ONVIFCamera('192.168.1.10', '8899', '', '')
  File "/usr/local/lib/python2.7/site-packages/onvif-0.1.3-py2.7.egg/onvif/client.py", line 258, in __init__
    self.update_xaddrs()
  File "/usr/local/lib/python2.7/site-packages/onvif-0.1.3-py2.7.egg/onvif/client.py", line 274, in update_xaddrs
    capabilities = self.devicemgmt.GetCapabilities({'Category': 'All'})
  File "/usr/local/lib/python2.7/site-packages/onvif-0.1.3-py2.7.egg/onvif/client.py", line 32, in wrapped
    raise ONVIFError(err)
onvif.exceptions.ONVIFError: Unknown error: <urlopen error [Errno 61] Connection refused>

**Comment by liuxue0905** [comment]
Half number of my camera device raise this error, When excute any Method, not only GetCapabilities.
