### ISSUE TITLE
Unknown error: 'NoneType' object has no attribute 'getroottree'

### ISSUE THREAD

**Issue by RenegadeMaster** [quatanium/python-onvif#80]
I get this error with any version (including zeep) and with any python version. What am I doing wrong? Is it a problem with the wsdl? Thanks. Full stacktrace:

Traceback (most recent call last):
  File "/home/dc/PycharmProjects/webcam/venv/lib/python3.5/site-packages/onvif/client.py", line 23, in wrapped
    return func(*args, **kwargs)
  File "/home/dc/PycharmProjects/webcam/venv/lib/python3.5/site-packages/onvif/client.py", line 153, in wrapped
    return call(params, callback)
  File "/home/dc/PycharmProjects/webcam/venv/lib/python3.5/site-packages/onvif/client.py", line 140, in call
    ret = func(**params)
  File "/home/dc/PycharmProjects/webcam/venv/lib/python3.5/site-packages/zeep/proxy.py", line 42, in __call__
    self._op_name, args, kwargs)
  File "/home/dc/PycharmProjects/webcam/venv/lib/python3.5/site-packages/zeep/wsdl/bindings/soap.py", line 132, in send
    return self.process_reply(client, operation_obj, response)
  File "/home/dc/PycharmProjects/webcam/venv/lib/python3.5/site-packages/zeep/wsdl/bindings/soap.py", line 170, in process_reply
    doc = parse_xml(content, self.transport, settings=client.settings)
  File "/home/dc/PycharmProjects/webcam/venv/lib/python3.5/site-packages/zeep/loader.py", line 50, in parse_xml
    forbid_entities=settings.forbid_entities)
  File "/home/dc/PycharmProjects/webcam/venv/lib/python3.5/site-packages/defusedxml/lxml.py", line 146, in fromstring
    elementtree = rootelement.getroottree()
AttributeError: 'NoneType' object has no attribute 'getroottree'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dc/pycharm-2019.1.1/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/home/dc/pycharm-2019.1.1/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/dc/pycharm-2019.1.1/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/dc/pycharm-2019.1.1/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/dc/PycharmProjects/webcam/main.py", line 25, in <module>
    main()
  File "/home/dc/PycharmProjects/webcam/main.py", line 5, in main
    mycam = ONVIFCamera('192.168.1.20', 80, 'admin', 'admin')
  File "/home/dc/PycharmProjects/webcam/venv/lib/python3.5/site-packages/onvif/client.py", line 216, in __init__
    self.update_xaddrs()
  File "/home/dc/PycharmProjects/webcam/venv/lib/python3.5/site-packages/onvif/client.py", line 233, in update_xaddrs
    capabilities = self.devicemgmt.GetCapabilities({'Category': 'All'})
  File "/home/dc/PycharmProjects/webcam/venv/lib/python3.5/site-packages/onvif/client.py", line 26, in wrapped
    raise ONVIFError(err)
onvif.exceptions.ONVIFError: Unknown error: 'NoneType' object has no attribute 'getroottree'

**Comment by Joylan** [comment]
Hello my friend, how fix this problem? I have the same error. Thanks!
