### ISSUE TITLE
How to perform absoluteMove or relative move

### ISSUE THREAD

**Issue by LoayMAmin** [quatanium/python-onvif#87]
Hello,
I have done continuous move successfully. Now I need to perform AbsoluteMove,
Could someone please send a working code sample of this, please? 

And does the onvif profile of the camra I'm using have to be something specific to make absolute/relative moves?

Thanks

**Comment by kindofausername** [comment]
Hello,
would be really nice to have an example of absolute/relative moves.

`requestr = ptz_service.create_type('AbsoluteMove')`
`requestr.ProfileToken = media_profile.token`
`requestr.Position = ptz_service.GetStatus({'ProfileToken': media_profile.token}).Position`
`ptz_service.RelativeMove(requestr, timeout=1)`

will bring the following error:

`Traceback (most recent call last):
  File "/Users/mymac/anaconda3/envs/onvif39/lib/python3.9/site-packages/onvif/client.py", line 140, in call
    ret = func(**params)
  File "/Users/mymac/anaconda3/envs/onvif39/lib/python3.9/site-packages/zeep/proxy.py", line 46, in __call__
    return self._proxy._binding.send(
  File "/Users/mymac/anaconda3/envs/onvif39/lib/python3.9/site-packages/zeep/wsdl/bindings/soap.py", line 123, in send
    envelope, http_headers = self._create(
  File "/Users/mymac/anaconda3/envs/onvif39/lib/python3.9/site-packages/zeep/wsdl/bindings/soap.py", line 73, in _create
    serialized = operation_obj.create(*args, **kwargs)
  File "/Users/mymac/anaconda3/envs/onvif39/lib/python3.9/site-packages/zeep/wsdl/definitions.py", line 222, in create
    return self.input.serialize(*args, **kwargs)
  File "/Users/mymac/anaconda3/envs/onvif39/lib/python3.9/site-packages/zeep/wsdl/messages/soap.py", line 73, in serialize
    body_value = self.body(*args, **kwargs)
  File "/Users/mymac/anaconda3/envs/onvif39/lib/python3.9/site-packages/zeep/xsd/elements/element.py", line 58, in __call__
    instance = self.type(*args, **kwargs)
  File "/Users/mymac/anaconda3/envs/onvif39/lib/python3.9/site-packages/zeep/xsd/types/complex.py", line 63, in __call__
    return self._value_class(*args, **kwargs)
  File "/Users/mymac/anaconda3/envs/onvif39/lib/python3.9/site-packages/zeep/xsd/valueobjects.py", line 106, in __init__
    items = _process_signature(self._xsd_type, args, kwargs)
  File "/Users/mymac/anaconda3/envs/onvif39/lib/python3.9/site-packages/zeep/xsd/valueobjects.py", line 241, in _process_signature
    raise TypeError(
TypeError: {http://www.onvif.org/ver20/ptz/wsdl}RelativeMove() got an unexpected keyword argument 'Position'. Signature: `ProfileToken: {http://www.onvif.org/ver10/schema}ReferenceToken, Translation: {http://www.onvif.org/ver10/schema}PTZVector, Speed: {http://www.onvif.org/ver10/schema}PTZSpeed`
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/mymac/anaconda3/envs/onvif39/lib/python3.9/site-packages/onvif/client.py", line 23, in wrapped
    return func(*args, **kwargs)
  File "/Users/mymac/anaconda3/envs/onvif39/lib/python3.9/site-packages/onvif/client.py", line 153, in wrapped
    return call(params, callback)
  File "/Users/mymac/anaconda3/envs/onvif39/lib/python3.9/site-packages/onvif/client.py", line 143, in call
    ret = func(params)
  File "/Users/mymac/anaconda3/envs/onvif39/lib/python3.9/site-packages/zeep/proxy.py", line 46, in __call__
    return self._proxy._binding.send(
  File "/Users/mymac/anaconda3/envs/onvif39/lib/python3.9/site-packages/zeep/wsdl/bindings/soap.py", line 123, in send
    envelope, http_headers = self._create(
  File "/Users/mymac/anaconda3/envs/onvif39/lib/python3.9/site-packages/zeep/wsdl/bindings/soap.py", line 73, in _create
    serialized = operation_obj.create(*args, **kwargs)
  File "/Users/mymac/anaconda3/envs/onvif39/lib/python3.9/site-packages/zeep/wsdl/definitions.py", line 222, in create
    return self.input.serialize(*args, **kwargs)
  File "/Users/mymac/anaconda3/envs/onvif39/lib/python3.9/site-packages/zeep/wsdl/messages/soap.py", line 79, in serialize
    self.body.render(body, body_value)
  File "/Users/mymac/anaconda3/envs/onvif39/lib/python3.9/site-packages/zeep/xsd/elements/element.py", line 232, in render
    self._render_value_item(parent, value, render_path)
  File "/Users/mymac/anaconda3/envs/onvif39/lib/python3.9/site-packages/zeep/xsd/elements/element.py", line 256, in _render_value_item
    return self.type.render(node, value, None, render_path)
  File "/Users/mymac/anaconda3/envs/onvif39/lib/python3.9/site-packages/zeep/xsd/types/complex.py", line 295, in render
    element.render(node, element_value, child_path)
  File "/Users/mymac/anaconda3/envs/onvif39/lib/python3.9/site-packages/zeep/xsd/elements/indicators.py", line 251, in render
    element.render(parent, element_value, child_path)
  File "/Users/mymac/anaconda3/envs/onvif39/lib/python3.9/site-packages/zeep/xsd/elements/element.py", line 232, in render
    self._render_value_item(parent, value, render_path)
  File "/Users/mymac/anaconda3/envs/onvif39/lib/python3.9/site-packages/zeep/xsd/elements/element.py", line 256, in _render_value_item
    return self.type.render(node, value, None, render_path)
  File "/Users/mymac/anaconda3/envs/onvif39/lib/python3.9/site-packages/zeep/xsd/types/simple.py", line 96, in render
    node.text = self.xmlvalue(value)
  File "/Users/mymac/anaconda3/envs/onvif39/lib/python3.9/site-packages/zeep/xsd/types/builtins.py", line 27, in _wrapper
    raise ValueError(
ValueError: The ReferenceToken type doesn't accept collections as value
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "<input>", line 3, in perform_moveABS
  File "/Users/mymac/anaconda3/envs/onvif39/lib/python3.9/site-packages/onvif/client.py", line 26, in wrapped
    raise ONVIFError(err)
onvif.exceptions.ONVIFError: Unknown error: The ReferenceToken type doesn't accept collections as value`


Greetings

**Comment by djsamseng** [comment]
The following works for me
```python
mycam = ONVIFCamera(IP, PORT, USER, PASS)
media = mycam.create_media_service()
media_profile = media.GetProfiles()[0]

request = ptz.create_type('GetConfigurationOptions')
request.ConfigurationToken = media_profile.PTZConfiguration.token
ptz_configuration_options = ptz.GetConfigurationOptions(request)

moverequest = ptz.create_type('RelativeMove')
moverequest.ProfileToken = media_profile.token
moverequest.Translation = {
    "PanTilt": {
        "x": 0.5, # set as desired
        "y": 0.5, # set as desired
        "space": ptz_configuration_options.Spaces.RelativePanTiltTranslationSpace[0].URI
    },
    "Zoom": {
        "x": 0,
        "space": ptz_configuration_options.Spaces.RelativeZoomTranslationSpace[0].URI
    }
}
ptz.RelativeMove(moverequest)
```

Additionally you can find the min and max values of x and y (and scale appropriately) under `ptz_configuration_options.Spaces.RelativePanTiltTranslationSpace[0].XRange.Min` etc.

Documentation is here: [RelativeMove request](https://github.com/onvif/specs/blob/af63a325b9ac9a3225b210692833829a3c8cf471/wsdl/ver20/ptz/wsdl/ptz.wsdl#L443) with member [Translation PTZVector](https://github.com/onvif/specs/blob/af63a325b9ac9a3225b210692833829a3c8cf471/wsdl/ver10/schema/common.xsd#L70)
