### ISSUE TITLE
Unknown error: (400, u'Bad Request') with Axis P7214

### ISSUE THREAD

**Issue by hackeron** [quatanium/python-onvif#9]
I enabled ONVIF and set up a user account for full admin rights on an Axis P7214 IP encoder, when I try to connect however I see:

```
mycam = ONVIFCamera('192.168.88.12', 80, 'root', 'password', '/etc/onvif/wsdl/')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "onvif/client.py", line 225, in __init__
    self.update_xaddrs()
  File "onvif/client.py", line 235, in update_xaddrs
    services = self.devicemgmt.GetServices({'IncludeCapability': False})
  File "onvif/client.py", line 30, in wrapped
    raise ONVIFError(err)
onvif.exceptions.ONVIFError: Unknown error: (400, u'Bad Request')
```

Any ideas?

**Comment by aguilar47** [comment]
I have the same issue and i think it might be because of a bad security token. Im currently looking into it.
